services:
    ds.user.repository.user:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments:
            - Oro\Bundle\UserBundle\Entity\User
