navigation:
    menu_config:
        items:
            ds_record_tab:
                label: ds.record.menu.tab.label
                uri: '#'
                extras:
                    position: 22
            ds_record_index:
                label: ds.record.menu.index.label
                route: ds_record_record_index
