ds_record:
    resource: @DsRecordBundle/Controller
    type: annotation

ds_record_api_rest:
    resource: @DsRecordBundle/Resources/config/oro/routing/api.yml
    type: rest
    prefix: %ds.api.rest.prefix%
    requirements:
        version: %ds.api.rest.requirements.version%
        _format: json
    defaults:
        version: %ds.api.rest.defaults.version%
