oro_menu_config:
    items:
        ds_status_index:
            label: ds.casestatus.status.menu.index.label
            route: ds_casestatus_status_index
    tree:
        application_menu:
            children:
                ds_case_tab:
                    children:
                        ds_status_index: ~
