services:
    ds.bpm_camunda.command.install:
        class: Ds\Bundle\BpmCamundaBundle\Command\InstallCommand
        tags:
            - { name: console.command }
    ds.bpm_camunda.command.start:
        class: Ds\Bundle\BpmCamundaBundle\Command\StartCommand
        tags:
            - { name: console.command }
    ds.bpm_camunda.command.stop:
        class: Ds\Bundle\BpmCamundaBundle\Command\StopCommand
        tags:
            - { name: console.command }
