oro_menu_config:
    items:
        ds_transport_tab:
            label: ds.transport.menu.tab.label
            uri: '#'
            extras:
                position: 21
        ds_transport_index:
            label: ds.transport.menu.index.label
            route: ds_transport_transport_index
        ds_profile_index:
            label: ds.transport.profile.menu.index.label
            route: ds_transport_profile_index
    tree:
        application_menu:
            children:
                system_tab:
                    children:
                        ds_transport_tab:
                            children:
                                ds_transport_index: ~
                                ds_profile_index: ~
