oro_menu_config:
    templates:
        ds_portal_main:
            template: DsPortalBundle:Portal:menu/main.html.twig
            currentClass: active
            ancestorClass: active
    items:
        ds_portal_portal_home_index:
            label: ds.portal.page.portal.home.index.title
            route: ds_portal_portal_home_index
            extras:
                position: 10
                showNonAuthorized: true
    tree:
        ds_portal_main:
            type: ds_portal_main
            children:
                ds_portal_portal_home_index: ~
