oro_system_configuration:
    groups:
        ds_bpm_camunda_camunda:
            title: ds.bpm_camunda.system_configuration.groups.bpm_camunda_camunda.title
            icon: icon-wrench
        ds_bpm_camunda_camunda_connection:
            title: ds.bpm_camunda.system_configuration.groups.bpm_camunda_camunda_connection.title
    fields:
        ds_bpm_camunda.host:
            data_type: string
            type: text
            options:
                label: ds.bpm_camunda.system_configuration.fields.host.label
                tooltip: ~
            priority: 1
    tree:
        system_configuration:
            platform:
                children:
                    ds_bpm:
                        children:
                            ds_bpm_camunda_camunda:
                                children:
                                    ds_bpm_camunda_camunda_connection:
                                        children:
                                            - ds_bpm_camunda.host
