oro_entity_config:
    record:
        entity:
            items:
                enabled:
                    options:
                        require_schema_update: true
                        priority: 250
                        default_value: false
                    form:
                        type: oro_entity_extend_association_choice
                        options:
                            block: associations
                            required: true
                            label: Enabled Records
                            association_class: 'DsRecordBundle:Record'
                immutable:
                    options:
                        auditable: false
