acls:
    ds.message.message.view:
        type: entity
        class: DsMessageBundle:Message
        permission: VIEW
    ds.message.message.create:
        type: entity
        class: DsMessageBundle:Message
        permission: CREATE
    ds.message.message.edit:
        type: entity
        class: DsMessageBundle:Message
        permission: EDIT
    ds.message.message.delete:
        type: entity
        class: DsMessageBundle:Message
        permission: DELETE
