datagrids:
    ds-message-message:
        extended_entity_name: Ds\Bundle\MessageBundle\Entity\Message
        source:
            acl_resource: ds.communication.message.view
            type: orm
            query:
                select:
                    - m.id
                    - m.title
                    - m.createdAt
                    - m.updatedAt
                from:
                    - { table: DsMessageBundle:Message, alias: m }
        inline_editing:
            enable: true
        columns:
            id:
                label: ds.message.message.id.label
            title:
                label: ds.message.title.label
            createdAt:
                label: ds.message.created_at.label
                frontend_type: datetime
            updatedAt:
                label: ds.message.updated_at.label
                frontend_type: datetime
        properties:
            id: ~
            update_link:
                type: url
                route: ds_message_message_edit
                params:
                    - id
            view_link:
                type: url
                route: ds_message_message_view
                params:
                    - id
            delete_link:
                type: url
                route: ds_message_api_rest_delete_message
                params:
                    - id
        sorters:
            columns:
                id:
                    data_name: m.id
                title:
                    data_name: m.title
                createdAt:
                    data_name: m.createdAt
                updatedAt:
                    data_name: m.updatedAt
            default:
                id: ASC
        filters:
            columns:
                title:
                    type: string
                    data_name: m.title
                createdAt:
                    type: datetime
                    data_name: m.createdAt
                updatedAt:
                    type: datetime
                    data_name: m.updatedAt
        actions:
            view:
                type: navigate
                label: ds.message.grid.actions.view
                link: view_link
                icon: eye
                acl_resource: ds.message.message.view
                rowAction: true
            update:
                type: navigate
                label: ds.message.grid.actions.update
                link: update_link
                icon: edit
                acl_resource: ds.message.message.edit
            delete:
                type: delete
                label: ds.message.grid.actions.delete
                link: delete_link
                icon: trash
                acl_resource: ds.message.message.delete
