navigation:
    menu_config:
        items:
            ds_message_message_tab:
                label: ds.message.menu.tab.label
                uri: '#'
                extras:
                    position: 20
            ds_message_message_index:
                label: ds.message.menu.index.label
                route: ds_message_message_index
                attributes:
                    class: oro-email-user-emails
        tree:
#            application_menu:
#                children:
#                    ds_message_message_tab:
#                        children:
#                            ds_message_message_index: ~
            usermenu:
                children:
                    ds_message_message_index: ~
