ds_message:
    resource: @DsMessageBundle/Controller
    type: annotation

ds_message_api_rest:
    resource: @DsMessageBundle/Resources/config/oro/routing/api.yml
    type: rest
    prefix: %ds.api.rest.prefix%
    requirements:
        version: %ds.api.rest.requirements.version%
        _format: json
    defaults:
        version: %ds.api.rest.defaults.version%
