datagrids:
    ds-template-template:
        extended_entity_name: Ds\Bundle\TemplateBundle\Entity\Template
        source:
            acl_resource: ds.template.template.view
            type: orm
            query:
                select:
                    - t.id
                    - t.title
                    - t.createdAt
                    - t.updatedAt
                from:
                    - { table: DsTemplateBundle:Template, alias: t }
        inline_editing:
            enable: true
        columns:
            id:
                label: ds.template.id.label
            title:
                label: ds.template.title.label
            createdAt:
                label: ds.template.created_at.label
                frontend_type: datetime
            updatedAt:
                label: ds.template.updated_at.label
                frontend_type: datetime
        properties:
            id: ~
            update_link:
                type: url
                route: ds_template_template_edit
                params:
                    - id
            view_link:
                type: url
                route: ds_template_template_view
                params:
                    - id
            delete_link:
                type: url
                route: ds_template_api_rest_delete_template
                params:
                    - id
        sorters:
            columns:
                id:
                    data_name: t.id
                title:
                    data_name: t.title
                createdAt:
                    data_name: t.createdAt
                updatedAt:
                    data_name: t.updatedAt
            default:
                id: ASC
        filters:
            columns:
                title:
                    type: string
                    data_name: t.title
                createdAt:
                    type: datetime
                    data_name: t.createdAt
                updatedAt:
                    type: datetime
                    data_name: t.updatedAt
        actions:
            view:
                type: navigate
                label: ds.template.grid.actions.view
                link: view_link
                icon: eye
                acl_resource: ds.template.template.view
                rowAction: true
            update:
                type: navigate
                label: ds.template.grid.actions.update
                link: update_link
                icon: edit
                acl_resource: ds.template.template.edit
            delete:
                type: delete
                label: ds.template.grid.actions.delete
                link: delete_link
                icon: trash
                acl_resource: ds.template.template.delete
