ds_communication:
    resource: @DsCommunicationBundle/Controller
    type: annotation

ds_communication_api_rest:
    resource: @DsCommunicationBundle/Resources/config/oro/routing/api.yml
    type: rest
    prefix: %ds.api.rest.prefix%
    requirements:
        version: %ds.api.rest.requirements.version%
        _format: json
    defaults:
        version: %ds.api.rest.defaults.version%
