ds_asset:
    resource: @DsAssetBundle/Controller
    type: annotation

ds_asset_api_rest:
    resource: @DsAssetBundle/Resources/config/oro/routing/api.yml
    type: rest
    prefix: %ds.api.rest.prefix%
    requirements:
        version: %ds.api.rest.requirements.version%
        _format: json
    defaults:
        version: %ds.api.rest.defaults.version%
