ds.case.case.view:
    type: entity
    class: DsCaseBundle:CaseEntity
    permission: VIEW

ds.case.case.create:
    type: entity
    class: DsCaseBundle:CaseEntity
    permission: CREATE

ds.case.case.edit:
    type: entity
    class: DsCaseBundle:CaseEntity
    permission: EDIT

ds.case.case.delete:
    type: entity
    class: DsCaseBundle:CaseEntity
    permission: DELETE
