oro_menu_config:
    items:
        ds_case_tab:
            label: ds.case.caseentity.menu.tab.label
            uri: '#'
            extras:
                position: 15
        ds_case_index:
            label: ds.case.caseentity.menu.index.label
            route: ds_case_case_index
    tree:
        application_menu:
            children:
                ds_case_tab:
                    children:
                        ds_case_index: ~
