oro_menu_config:
    items:
        ds_accountuserpersona_account_persona_index:
            label: ds.accountuserpersona.persona.page.account.index.title
            route: ds_accountuserpersona_account_persona_index
            extras:
                position: 40
    tree:
        ds_account_main:
            children:
                ds_accountuserpersona_account_persona_index: ~
