ds.service.activation.view:
    type: entity
    class: DsServiceBundle:Activation
    permission: VIEW

ds.service.activation.create:
    type: entity
    class: DsServiceBundle:Activation
    permission: CREATE

ds.service.activation.edit:
    type: entity
    class: DsServiceBundle:Activation
    permission: EDIT

ds.service.activation.delete:
    type: entity
    class: DsServiceBundle:Activation
    permission: DELETE

ds.service.service.view:
    type: entity
    class: DsServiceBundle:Service
    permission: VIEW

ds.service.service.create:
    type: entity
    class: DsServiceBundle:Service
    permission: CREATE

ds.service.service.edit:
    type: entity
    class: DsServiceBundle:Service
    permission: EDIT

ds.service.service.delete:
    type: entity
    class: DsServiceBundle:Service
    permission: DELETE
