services:
    ds.transport.data.resolver.profile:
        class: Ds\Bundle\TransportBundle\Data\Resolver\ProfileResolver
        arguments:
            - @ds.transport.manager.profile
        tags:
            - { name: ds.data.resolver }
    ds.transport.data.resolver.transport:
        class: Ds\Bundle\TransportBundle\Data\Resolver\TransportResolver
        arguments:
            - @ds.transport.manager.transport
        tags:
            - { name: ds.data.resolver }
