services:
    ds.transport.repository.profile:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments:
            - Ds\Bundle\TransportBundle\Entity\Profile
    ds.transport.repository.transport:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments:
            - Ds\Bundle\TransportBundle\Entity\Transport
