services:
    ds.portal.event.listener.locale:
        class: Ds\Bundle\PortalBundle\Event\Listener\LocaleListener
        arguments:
            - @request_stack
            - @translator
        tags:
            - { name: kernel.event_listener, event: kernel.request }
    ds.portal.event.listener.navigation:
        class: Ds\Bundle\PortalBundle\Event\Listener\NavigationListener
        arguments:
            - @request_stack
        tags:
            - { name: kernel.event_listener, event: oro_menu.configure.ds_portal_main, method: onNavigationConfigure }
