oro_menu_config:
    items:
        ds_portalservice_portal_service_index:
            label: ds.portalservice.service.page.portal.index.title
            route: ds_portalservice_portal_service_index
            extras:
                position: 20
                showNonAuthorized: true
    tree:
        ds_portal_main:
            children:
                ds_portalservice_portal_service_index: ~
