ds_service:
    resource: @DsServiceBundle/Controller
    type: annotation

ds_service_api_rest:
    resource: @DsServiceBundle/Resources/config/oro/routing/api.yml
    type: rest
    prefix: %ds.api.rest.prefix%
    requirements:
        version: %ds.api.rest.requirements.version%
        _format: json
    defaults:
        version: %ds.api.rest.defaults.version%
