ds_accountuserpersona_account:
    resource: @DsAccountUserPersonaBundle/Controller/Account
    type: annotation
    prefix: %ds.account.prefix%
    requirements:
        _locale: %ds.account.requirements.locale%
    defaults:
        _locale: %ds.account.defaults.locale%
