placeholders:
    ds_service_service_button_create:
        items:
            ds_servicebpm_service_button_create:
                order: 101

items:
    ds_servicebpm_service_button_create:
        template: DsServiceBpmBundle:ServiceBpm:widget/button/create.html.twig
        acl: [ ds.service.service.create ]
