oro_menu_config:
    items:
        ds_accountcase_account_case_index:
            label: ds.accountcase.page.account.caseentity.index.title
            route: ds_accountcase_account_case_index
            extras:
                position: 20
    tree:
        ds_account_main:
            children:
                ds_accountcase_account_case_index: ~
