ds_case:
    resource: @DsCaseBundle/Controller
    type: annotation

ds_case_api_rest:
    resource: @DsCaseBundle/Resources/config/oro/routing/api.yml
    type: rest
    prefix: %ds.api.rest.prefix%
    requirements:
        version: %ds.api.rest.requirements.version%
        _format: json
    defaults:
        version: %ds.api.rest.defaults.version%
