navigation:
    menu_config:
        templates:
            ds_portal_main:
                template: DsPortalBundle:Portal:menu/main.html.twig
                current_class: active
                ancestor_class: active
        tree:
            ds_portal_main:
                type: ds_portal_main

