navigation:
    menu_config:
        items:
            ds_portalnotification_portal_notification_index:
                label: ds.portalnotification.page.portal.notification.index.title
                route: ds_portalnotification_portal_notification_index
                extras:
                    position: 30
                    show_non_authorized: true
        tree:
            ds_portal_main:
                children:
                    ds_portalnotification_portal_notification_index: ~
