ds_portalnotification_portal:
    resource: @DsPortalNotificationBundle/Controller/Portal
    type: annotation
    prefix: %ds.portal.prefix%
    requirements:
        _locale: %ds.portal.requirements.locale%
    defaults:
        _locale: %ds.portal.defaults.locale%
