services:
    ds.message.data.resolver.message:
        class: Ds\Bundle\MessageBundle\Data\Resolver\MessageResolver
        arguments:
            - @ds.message.manager.message
        tags:
            - { name: ds.data.resolver }
