services:
    ds.message.form.type.message:
        class: Ds\Bundle\MessageBundle\Form\Type\MessageType
        tags:
            - { name: form.type, alias: ds_message_message }
    ds.message.form.type.api.message:
        class: Ds\Bundle\MessageBundle\Form\Type\Api\MessageType
        tags:
            - { name: form.type, alias: ds_message_api_message }
    ds.message.form.api.message:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - ~
            - ds_message_api_message
    ds.message.form.handler.message:
        class: Ds\Bundle\MessageBundle\Form\Handler\MessageHandler
        scope: request
        arguments:
            - @ds.message.form.api.message
            - @request
            - @doctrine.orm.entity_manager
