services:
    ds.message.widget.message.entity:
        parent: ds.widget.widget.abstract
        class: Ds\Bundle\MessageBundle\Widget\Message\EntityWidget
        tags:
            - { name: ds.widget, position: ds_message_message_entity }
    ds.message.widget.message.form:
        parent: ds.widget.widget.abstract
        class: Ds\Bundle\MessageBundle\Widget\Message\FormWidget
        tags:
            - { name: ds.widget, position: ds_message_message_form }
    ds.message.widget.message.owner:
        parent: ds.widget.widget.abstract
        class: Ds\Bundle\MessageBundle\Widget\Message\OwnerWidget
        tags:
            - { name: ds.widget, position: ds_message_message_form }
