services:
     ds.asset.migration.extension.asset:
        class: Ds\Bundle\AssetBundle\Migration\Extension\AssetExtension
        tags:
            - { name: oro_migration.extension, extension_name: asset }
