oro_menu_config:
    items:
        ds_asset_tab:
            label: ds.asset.menu.tab.label
            uri: '#'
            extras:
                position: 22
        ds_asset_index:
            label: ds.asset.menu.index.label
            route: ds_asset_asset_index
    tree:
        application_menu:
            children:
                system_tab:
                    children:
                        ds_asset_tab:
                            children:
                                ds_asset_index: ~
