services:
    ds.asset.repository.asset:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments:
            - Ds\Bundle\AssetBundle\Entity\Asset
