placeholders:
    placeholders:
        oro_user_login_form:
            items:
                ds_sso_twitter_oauth_login: ~

    items:
        ds_sso_twitter_oauth_login:
            template: DsSSOTwitterBundle:Security:oauth_login.html.twig
