acls:
    ds.notification.notification.view:
        type: entity
        class: DsNotificationBundle:Notification
        permission: VIEW

    ds.notification.notification.create:
        type: entity
        class: DsNotificationBundle:Notification
        permission: CREATE

    ds.notification.notification.edit:
        type: entity
        class: DsNotificationBundle:Notification
        permission: EDIT

    ds.notification.notification.delete:
        type: entity
        class: DsNotificationBundle:Notification
        permission: DELETE

    ds.notification.subscription.view:
        type: entity
        class: DsNotificationBundle:Subscription
        permission: VIEW

    ds.notification.subscription.create:
        type: entity
        class: DsNotificationBundle:Subscription
        permission: CREATE

    ds.notification.subscription.edit:
        type: entity
        class: DsNotificationBundle:Subscription
        permission: EDIT

    ds.notification.subscription.delete:
        type: entity
        class: DsNotificationBundle:Subscription
        permission: DELETE
