placeholders:
    ds_service_service_button_create:
        items:
            ds_serviceurl_service_button_create:
                order: 100

items:
    ds_serviceurl_service_button_create:
        template: DsServiceUrlBundle:ServiceUrl:widget/button/create.html.twig
        acl: [ ds.service.service.create ]
