services:
    ds.serviceurl.repository.serviceurl:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments:
            - Ds\Bundle\ServiceUrlBundle\Entity\ServiceUrl
