oro_system_configuration:
    groups:
        ds_sso_linkedin_settings:
            title: ds.sso_linkedin.system_configuration.groups.sso_linkedin_settings
    fields:
        ds_sso_linkedin.enabled:
            data_type: boolean
            type: oro_config_checkbox
            options:
                label: ds.sso_linkedin.system_configuration.fields.enabled
                tooltip: ~
                required: false
                resettable: false
            priority: 3
        ds_sso_linkedin.create_user:
            data_type: boolean
            type: oro_config_checkbox
            options:
                label: ds.sso_linkedin.system_configuration.fields.create_user
                tooltip: ~
                required: false
                resettable: false
            priority: 2
        ds_sso_linkedin.associate_user:
            data_type: boolean
            type: oro_config_checkbox
            options:
                label: ds.sso_linkedin.system_configuration.fields.associate_user
                tooltip: ~
                required: false
                resettable: false
            priority: 1
    tree:
        system_configuration:
            platform:
                children:
                    integrations:
                        children:
                            ds_linkedin:
                                children:
                                    ds_sso_linkedin_settings:
                                        children:
                                            - ds_sso_linkedin.enabled
                                            - ds_sso_linkedin.create_user
                                            - ds_sso_linkedin.associate_user
