oro_system_configuration:
    groups:
        ds_sso_linkedin_settings:
            title: ds.sso_linkedin.system_configuration.groups.sso_linkedin_settings
    fields:
        ds_sso_linkedin.enable_sso:
            data_type: boolean
            type: oro_config_checkbox
            options:
                label: ds.sso_linkedin.system_configuration.fields.enable_sso
                tooltip: ~
                required: false
                resettable: false
            priority: 1
    tree:
        system_configuration:
            platform:
                children:
                    integrations:
                        children:
                            ds_linkedin:
                                children:
                                    ds_sso_linkedin_settings:
                                        children:
                                            - ds_sso_linkedin.enable_sso
