services:
    ds.communication.form.type.channel:
        class: Ds\Bundle\CommunicationBundle\Form\Type\ChannelType
        arguments:
            - @ds.communication.collection.channel
        tags:
            - { name: form.type, alias: ds_communication_channel }
    ds.communication.form.type.api.channel:
        class: Ds\Bundle\CommunicationBundle\Form\Type\Api\ChannelType
        tags:
            - { name: form.type, alias: ds_communication_api_channel }
    ds.communication.form.api.channel:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - ~
            - ds_communication_api_channel
    ds.communication.form.handler.channel:
        class: Ds\Bundle\CommunicationBundle\Form\Handler\ChannelHandler
        scope: request
        arguments:
            - @ds.communication.form.api.channel
            - @request
            - @doctrine.orm.entity_manager
    ds.communication.form.type.communication:
        class: Ds\Bundle\CommunicationBundle\Form\Type\CommunicationType
        tags:
            - { name: form.type, alias: ds_communication_communication }
    ds.communication.form.type.api.communication:
        class: Ds\Bundle\CommunicationBundle\Form\Type\Api\CommunicationType
        tags:
            - { name: form.type, alias: ds_communication_api_communication }
    ds.communication.form.api.communication:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - ~
            - ds_communication_api_communication
    ds.communication.form.handler.communication:
        class: Ds\Bundle\CommunicationBundle\Form\Handler\CommunicationHandler
        scope: request
        arguments:
            - @ds.communication.form.api.communication
            - @request
            - @doctrine.orm.entity_manager
    ds.communication.form.type.content:
        class: Ds\Bundle\CommunicationBundle\Form\Type\ContentType
        tags:
            - { name: form.type, alias: ds_communication_content }
    ds.communication.form.type.api.content:
        class: Ds\Bundle\CommunicationBundle\Form\Type\Api\ContentType
        tags:
            - { name: form.type, alias: ds_communication_api_content }
    ds.communication.form.api.content:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - ~
            - ds_communication_api_content
    ds.communication.form.handler.content:
        class: Ds\Bundle\CommunicationBundle\Form\Handler\ContentHandler
        scope: request
        arguments:
            - @ds.communication.form.api.content
            - @request
            - @doctrine.orm.entity_manager
    ds.communication.form.type.criterion:
        class: Ds\Bundle\CommunicationBundle\Form\Type\CriterionType
        arguments:
            - @ds.communication.collection.criterion
        tags:
            - { name: form.type, alias: ds_communication_criterion }
    ds.communication.form.type.api.criterion:
        class: Ds\Bundle\CommunicationBundle\Form\Type\Api\CriterionType
        tags:
            - { name: form.type, alias: ds_communication_api_criterion }
    ds.communication.form.api.criterion:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - ~
            - ds_communication_api_criterion
    ds.communication.form.handler.criterion:
        class: Ds\Bundle\CommunicationBundle\Form\Handler\CriterionHandler
        scope: request
        arguments:
            - @ds.communication.form.api.criterion
            - @request
            - @doctrine.orm.entity_manager
    ds.communication.form.type.message:
        class: Ds\Bundle\CommunicationBundle\Form\Type\MessageType
        tags:
            - { name: form.type, alias: ds_communication_message }
    ds.communication.form.type.api.message:
        class: Ds\Bundle\CommunicationBundle\Form\Type\Api\MessageType
        tags:
            - { name: form.type, alias: ds_communication_api_message }
    ds.communication.form.api.message:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - ~
            - ds_communication_api_message
    ds.communication.form.handler.message:
        class: Ds\Bundle\CommunicationBundle\Form\Handler\MessageHandler
        scope: request
        arguments:
            - @ds.communication.form.api.message
            - @request
            - @doctrine.orm.entity_manager
    ds.communication.form.type.template:
        class: Ds\Bundle\CommunicationBundle\Form\Type\TemplateType
        tags:
            - { name: form.type, alias: ds_communication_template }
    ds.communication.form.type.api.template:
        class: Ds\Bundle\CommunicationBundle\Form\Type\Api\TemplateType
        tags:
            - { name: form.type, alias: ds_communication_api_template }
    ds.communication.form.api.template:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - ~
            - ds_communication_api_template
    ds.communication.form.handler.template:
        class: Ds\Bundle\CommunicationBundle\Form\Handler\TemplateHandler
        scope: request
        arguments:
            - @ds.communication.form.api.template
            - @request
            - @doctrine.orm.entity_manager
