oro_menu_config:
    items:
        ds_portalnotification_portal_notification_index:
            label: ds.portalnotification.notification.page.portal.index.title
            route: ds_portalnotification_portal_notification_index
            extras:
                position: 30
                showNonAuthorized: true
    tree:
        ds_portal_main:
            children:
                ds_portalnotification_portal_notification_index: ~
