system_configuration:
    groups:
        ds_twitter:
            title: ds.twitter.system_configuration.groups.twitter
            icon: fa-twitter
        ds_twitter_settings:
            title: ds.twitter.system_configuration.groups.twitter_settings
    fields:
        ds_twitter.client_id:
            data_type: string
            type: text
            options:
                label: ds.twitter.system_configuration.fields.client_id
                tooltip: ~
                required: false
                resettable: false
            priority: 2
        ds_twitter.client_secret:
            data_type: string
            type: text
            options:
                label: ds.twitter.system_configuration.fields.client_secret
                tooltip: ~
                required: false
                resettable: false
            priority: 1
    tree:
        system_configuration:
            platform:
                children:
                    integrations:
                        children:
                            ds_twitter:
                                children:
                                    ds_twitter_settings:
                                        children:
                                            - ds_twitter.client_id
                                            - ds_twitter.client_secret
