oro_menu_config:
    items:
        ds_accountbpm_account_task_index:
            label: ds.accountbpm.task.page.account.index.title
            route: ds_accountbpm_account_task_index
            extras:
                position: 30
    tree:
        ds_account_main:
            children:
                ds_accountbpm_account_task_index: ~
