oro_menu_config:
    templates:
        ds_account_main:
            template: DsAccountBundle:Account:menu/main.html.twig
            currentClass: active
            ancestorClass: active
    tree:
        ds_account_main:
            type: ds_account_main
